config/routes.rb
Rails.application.routes.draw do
  
  get 'stamps/create'
  get 'stamps/comp'

  devise_for :users
  resources :stamps

  get "home/top" => "home#top"
  root 'stamps#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stamp.rb
class Stamp < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :stamps, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

  protected
	def after_sign_out_path_for(resource_or_scope)
  		new_user_registration_path
  	end

  	def after_sign_in_path_for(resource_or_scope)
	    stamps_url
  	end
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.stamps.length == 0
      pl = ["受付","一階","二階","三階","三階VR"]
      for n in 0..4 do
        stamp = Stamp.new
        stamp = current_user.stamps.new
        stamp.place = pl[n]
        stamp.save!
      end
    end
  	@stamps = current_user.stamps
  end

  def create
  # 	pl = ["アトリウム","階段","二階右","二階左"]
  # 	for n in 0..3 do
  # 		stamp = Stamp.new
  # 		stamp = current_user.stamps.new
  # 		stamp.place = pl[n]
  # 		stamp.save!
	 # end

	redirect_to stamps_url
  end

  def edit
    @stamp = target_stamp params[:id]
  end

  def update
    @stamp = target_stamp params[:id]
    @stamp.update(stamp_params)
    redirect_to stamps_url
  end

  def comp
  end


  private

  	def target_stamp stamp_id
      current_user.stamps.find_by(id: stamp_id)
    end

    def stamp_params
      params.require(:stamp).permit(:place, :get)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stamps_helper.rb
module StampsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geiko2019AR</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Mandali|PT+Sans|Patua+One&display=swap" rel="stylesheet">
  <link rel="manifest" href="/manifest.json" />
<meta name="apple-mobile-web-app-capable" content="yes">
<%= stylesheet_link_tag "application", :media => "all" %>
  </head>

  <body>
    <% if user_signed_in? %>
    <header>
      <%= image_tag "head.png" %>
      <div class="user_name"><%= current_user.email.split('@')[0] %></div>
    </header>
    <% end %>
<!--     <p class="notice"><%= notice %></p> -->
<!--     <p class="alert"><%= alert %></p> -->
    <%= yield %>
      <!-- <% if user_signed_in? %>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
      <% end %> -->
  </body>
</html>

app/views/stamps/comp.html.erb
<div class="ar" id="ar" style="margin:0px; overflow:hidden;">
</div>
<footer>
	<%= link_to image_tag('return.png'), stamps_url, class: "return" %>
</footer>
<%= image_tag "get.png", class: "comp_get" %>

app/views/stamps/edit.html.erb
<% a = 0 %>
<div class="ar"></div>
<footer>
<%= link_to image_tag('return.png'), stamps_url, class: "return" %>
<%= form_for(@stamp) do |f| %>
  <% if a == 1 %>
    <%= f.hidden_field :get, value: true %>
  <% else %>
    <%= f.hidden_field :get, value: false %>
  <% end %>
  <%= button_tag type: :submit do %>
      <%= image_tag "get.png", class: "get" %>
  <% end %>
<% end %>
</footer>

app/views/stamps/index.html.erb
<% get_num = 0 %>
<% i = 1 %>
<% st = [false,false,false,false,false] %>
<div class="container" id = "">
	<p style="width: 70vw; margin-top: 8vh;">スタンプ５つ集めたらcompleteをタップできるよ！映像スタジオで取得できるよ。</p>
<%= image_tag "camera_nav" ,style: "width: 70vw; margin: 5vh 0 5vh 0"%>
<div class="stamps">
<% @stamps.each do | stamp | %>
	<% if stamp.get %>
		<% st[i-1] = true %>
		<% get_num += 1 %>
	<% end %>
	<% i += 1 %>
<% end %>

<div class="st_img st1">
	<% if st[0] %>
		<%= image_tag "get1" %>
	<% else %>
		<%= link_to image_tag("st1"), edit_stamp_path(@stamps[0]) %>
	<% end %>
</div>
<div class="st_img st2">
	<% if st[1] %>
		<%= image_tag "get2" %>
	<% else %>
		<%= link_to image_tag("st2"), edit_stamp_path(@stamps[1]) %>
	<% end %>
</div>
<div class="st_img st3">
	<% if st[2] %>
		<%= image_tag "get3" %>
	<% else %>
		<%= link_to image_tag("st3"), edit_stamp_path(@stamps[2]) %>
	<% end %>
</div>
<div class="st_img st4">
	<% if st[3] %>
		<%= image_tag "get4" %>
	<% else %>
		<%= link_to image_tag("st4"), edit_stamp_path(@stamps[3]) %>
	<% end %>
</div>
<div class="st_img st5">
	<% if st[4] %>
		<%= image_tag "get5" %>
	<% else %>
		<%= link_to image_tag("st5"), edit_stamp_path(@stamps[4]) %>
	<% end %>
</div>
</div>

<div class="comp">
	<% if get_num == 5 %>
		<%= link_to image_tag("comp.png"), stamps_comp_path %>
		<% get_num += 1 %>
	<% else %>
		<%= image_tag "comp_no.png" %>
	<% end %>
</div>
<div class="go_top">
	<%= link_to image_tag("page_top") ,{ anchor: "top" }%>
</div>

<script type="text/javascript">
	$(function(){
     // #で始まるアンカーをクリックした場合に処理
    $('.go_top').click(function() {
        $('html,body').animate({ scrollTop: 0,scrollLeft: 0 }, '1');
    });
});
</script>
</div>